<a href="https://colab.research.google.com/github/tajeshwar74/scikit-learn/blob/main/ScikitLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Train_Test_Split

In [ ]:
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/content/sample_data/500hits.csv", encoding="latin-1")

In [ ]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [ ]:
X = df.drop(columns=['PLAYER', 'HOF'])

In [ ]:
y = df['HOF']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 11, test_size=0.2)

In [ ]:
X_train.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
289,18,2028,7298,873,1993,284,40,325,1163,620,1313,20,38,0.273
288,13,1836,6826,856,1996,392,117,43,402,513,360,247,108,0.292
350,14,1799,6373,876,1854,282,64,49,630,844,627,37,51,0.291
196,17,2158,7911,1057,2276,414,92,94,844,690,784,246,138,0.288
184,19,2390,8570,1386,2369,420,65,244,1084,1197,1099,143,75,0.276

In [ ]:
X_train.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
count,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000
mean,17.010753,2046.521505,7526.077957,1154.126344,2177.994624,382.505376,78.094086,202.642473,901.072581,780.104839,850.322581,196.927419,58.986559,0.289164
std,2.662486,351.232903,1302.405807,291.308439,426.615256,97.173380,48.798439,141.726317,484.370314,327.453126,472.917969,185.585713,49.322224,0.021069
min,11.000000,1331.000000,4981.000000,651.000000,1660.000000,177.000000,3.000000,9.000000,0.000000,239.000000,0.000000,7.000000,0.000000,0.246000
25%,15.000000,1797.500000,6507.500000,936.000000,1838.000000,312.000000,41.000000,79.750000,645.000000,536.500000,448.000000,64.500000,23.000000,0.274000
50%,17.000000,1992.000000,7237.000000,1099.000000,2080.500000,367.000000,67.000000,185.500000,977.500000,719.000000,844.000000,141.000000,52.000000,0.288000
75%,19.000000,2245.500000,8198.250000,1305.000000,2383.750000,436.250000,108.000000,293.250000,1218.500000,961.250000,1234.250000,285.500000,84.000000,0.300250
max,26.000000,3308.000000,12364.000000,2295.000000,4189.000000,792.000000,309.000000,755.000000,2297.000000,2190.000000,1936.000000,1406.000000,335.000000,0.366000

#Normalization & Standardization

In [ ]:
df = df.drop(columns=['PLAYER', 'CS'])

In [ ]:
X1 = df.iloc[:, 0:13]

In [ ]:
X2 = df.iloc[:, 0:13]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaleStandard = StandardScaler()

In [ ]:
X1 = scaleStandard.fit_transform(X1)

In [ ]:
X1 = pd.DataFrame(X1, columns=['YRS', 'G', 'AB','R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'BA'])

In [ ]:
X1.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,3.648290
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,1.996159
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,2.657012
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,1.004881
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,1.901752

In [ ]:
X1.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,-0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,0.000,0.000,-0.000,0.000,0.000
std,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001
min,-2.190,-2.027,-1.958,-1.899,-1.204,-2.116,-1.532,-1.339,-1.841,-1.665,-1.734,-1.040,-2.016
25%,-0.742,-0.697,-0.765,-0.741,-0.784,-0.715,-0.762,-0.851,-0.524,-0.760,-0.842,-0.732,-0.742
50%,-0.018,-0.157,-0.209,-0.160,-0.222,-0.155,-0.234,-0.161,0.152,-0.145,-0.046,-0.324,-0.081
75%,0.706,0.560,0.517,0.504,0.483,0.571,0.577,0.634,0.642,0.524,0.775,0.490,0.533
max,3.240,3.557,3.754,3.956,4.764,4.265,4.673,3.861,2.888,4.300,3.580,6.662,3.648

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaleMinMax = MinMaxScaler(feature_range=(0,1))

In [ ]:
X2 = scaleMinMax.fit_transform(X2)

In [ ]:
X2 = pd.DataFrame(X2, columns=['YRS', 'G', 'AB','R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'BA'])

In [ ]:
X2.head().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,0.867,0.862,0.874,0.971,1.000,0.889,0.954,0.145,0.316,0.518,0.137,0.633,1.000
1,0.733,0.857,0.811,0.796,0.779,0.891,0.569,0.625,0.849,0.697,0.268,0.051,0.708
2,0.733,0.737,0.706,0.756,0.733,1.000,0.716,0.145,0.315,0.585,0.085,0.304,0.825
3,0.600,0.716,0.842,0.780,0.714,0.597,0.206,0.336,0.571,0.432,0.709,0.251,0.533
4,0.667,0.739,0.738,0.670,0.700,0.753,0.814,0.123,0.000,0.371,0.126,0.511,0.692

In [ ]:
X2.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,0.403,0.363,0.343,0.324,0.202,0.332,0.247,0.257,0.389,0.279,0.326,0.135,0.356
std,0.184,0.179,0.175,0.171,0.168,0.157,0.161,0.193,0.212,0.168,0.188,0.130,0.177
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.267,0.238,0.209,0.198,0.070,0.220,0.124,0.094,0.279,0.152,0.168,0.040,0.225
50%,0.400,0.335,0.306,0.297,0.164,0.307,0.209,0.227,0.421,0.255,0.318,0.093,0.342
75%,0.533,0.463,0.433,0.410,0.283,0.421,0.340,0.379,0.525,0.367,0.472,0.199,0.450
max,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000